name: SKYT Tunnel

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install Docker
      uses: docker/setup-buildx-action@v3

    - name: Build Docker Proxy
      run: docker build -t proxy .

    - name: Run TinyProxy
      run: docker run -d -p 8888:8888 proxy

    - name: Start Cloudflare Tunnel
      run: |
        curl -fsSL https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -o cloudflared
        chmod +x cloudflared
        ./cloudflared tunnel --url http://localhost:8888
